In [2]:
#Add the Elements of Two Lists
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = []

for i, j in zip(x, y):
  z.append(i + j)
print(z)

[5, 7, 9, 11]


In [6]:
import numpy as np
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = np.add(x, y)
print(z)

[ 5  7  9 11]


In [8]:
def myadd(x, y):
  return x+y

myadd = np.frompyfunc(myadd, 2, 1)

print(myadd([1, 2, 3, 4], [5, 6, 7, 8]))

[6 8 10 12]


In [10]:
if type(np.add) == np.ufunc:
  print('add is ufunc')
else:
  print('add is not ufunc')

add is ufunc


In [12]:
#Addition
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])
newarr = np.add(arr1, arr2)
print(newarr)

[30 32 34 36 38 40]


In [14]:
#Subtraction
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])
newarr = np.subtract(arr1, arr2)
print(newarr)

[-10  -1   8  17  26  35]


In [16]:
#Multiplication
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])
newarr = np.multiply(arr1, arr2)
print(newarr)

[ 200  420  660  920 1200 1500]


In [19]:
#Division
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 10, 8, 2, 33])
newarr = np.divide(arr1, arr2)
print(newarr)

[ 3.33333333  4.          3.          5.         25.          1.81818182]


In [21]:
#Power
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 6, 8, 2, 33])
newarr = np.power(arr1, arr2)
print(newarr)

[         1000       3200000     729000000 6553600000000          2500
             0]


In [23]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])
newarr = np.mod(arr1, arr2)
print(newarr)

[ 1  6  3  0  0 27]


In [25]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])
newarr = np.remainder(arr1, arr2)
print(newarr)

[ 1  6  3  0  0 27]


In [27]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])
newarr = np.divmod(arr1, arr2)
print(newarr)
# The example above will return:
# (array([3, 2, 3, 5, 25, 1]), array([1, 6, 3, 0, 0, 27]))
# The first array represents the quotients, (the integer value when you divide 10 with 3, 20 with 7, 30 with 9 etc.
# The second array represents the remainders of the same divisions.

(array([ 3,  2,  3,  5, 25,  1]), array([ 1,  6,  3,  0,  0, 27]))


In [29]:
#Absolute Values
arr = np.array([-1, -2, 1, 2, 3, -4])
newarr = np.absolute(arr)
print(newarr)

[1 2 1 2 3 4]


In [30]:
# truncation
# fix
# rounding
# floor
# ceil

In [32]:
arr = np.trunc([-3.1666, 3.6667])
print(arr)

[-3.  3.]


In [34]:
arr = np.fix([-3.1666, 3.6667])
print(arr)

[-3.  3.]


In [36]:
#Rounding
arr = np.around(3.1666, 2)
print(arr)

3.17


In [38]:
#Floor
arr = np.floor([-3.1666, 3.6667])
print(arr)

[-4.  3.]


In [40]:
#Ceil
arr = np.ceil([-3.1666, 3.6667])
print(arr)

[-3.  4.]


In [42]:
#NumPy Logs
#Log at Base 2
arr = np.arange(1, 10)
print(np.log2(arr))

[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


In [44]:
#Log at Base 10
arr = np.arange(1, 10)
print(np.log10(arr))

[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]


In [46]:
#Use the log() function to perform log at the base e.
arr = np.arange(1, 10)
print(np.log(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


In [49]:
#Log at Any Base
from math import log
import numpy as np
nplog = np.frompyfunc(log, 2, 1)
print(nplog(100, 15))

1.7005483074552052


In [51]:
#Add the values in arr1 to the values in arr2:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])
newarr = np.add(arr1, arr2)
print(newarr)

[2 4 6]


In [53]:
#Sum the values in arr1 and the values in arr2:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])
newarr = np.sum([arr1, arr2])
print(newarr)

12


In [55]:
#Perform summation in the following array over 1st axis:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])
newarr = np.sum([arr1, arr2], axis=1)
print(newarr)

[6 6]


In [57]:
arr = np.array([1, 2, 3])
newarr = np.cumsum(arr)
print(newarr)

[1 3 6]


In [61]:
#NumPy Products
#use the prod() function
arr = np.array([1, 2, 3, 4])
x = np.prod(arr)
print(x)

24


In [63]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
x = np.prod([arr1, arr2])
print(x)

40320


In [65]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
newarr = np.prod([arr1, arr2], axis=1)
print(newarr)

[  24 1680]


In [67]:
#Cummulative Product
arr = np.array([5, 6, 7, 8])
newarr = np.cumprod(arr)
print(newarr)

[   5   30  210 1680]


In [71]:
# NumPy Differences
arr = np.array([10, 15, 25, 5])
newarr = np.diff(arr)
print(newarr)

[  5  10 -20]


In [75]:
# n=2 means do it twice
import numpy as np
arr = np.array([10, 15, 25, 5])
newarr = np.diff(arr, n=2)
print(newarr)

[  5 -30]


In [77]:
#NumPy LCM Lowest Common Multiple
num1 = 4
num2 = 6
x = np.lcm(num1, num2)
print(x)

12


In [79]:
arr = np.array([3, 6, 9])
x = np.lcm.reduce(arr)
print(x)

18


In [81]:
arr = np.arange(1, 11)
x = np.lcm.reduce(arr)
print(x)

2520


In [84]:
#The GCD (Greatest Common Divisor), also known as HCF (Highest Common Factor) is the biggest number that is a common factor of both of the numbers.
num1 = 6
num2 = 9
x = np.gcd(num1, num2)
print(x)
#Returns: 3 because that is the highest number both numbers can be divided by (6/3=2 and 9/3=3).

3


In [86]:
import numpy as np
arr = np.array([20, 8, 32, 36, 16])
x = np.gcd.reduce(arr)
print(x)

4


In [88]:
#NumPy Trigonometric Functions
x = np.sin(np.pi/2)
print(x)

1.0


In [90]:
#Find sine values for all of the values in arr:
arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])
x = np.sin(arr)
print(x)

[1.         0.8660254  0.70710678 0.58778525]


In [92]:
#Convert Degrees Into Radians
arr = np.array([90, 180, 270, 360])
x = np.deg2rad(arr)
print(x)

[1.57079633 3.14159265 4.71238898 6.28318531]


In [94]:
#Radians to Degrees
arr = np.array([90, 180, 270, 360])
x = np.deg2rad(arr)
print(x)

[1.57079633 3.14159265 4.71238898 6.28318531]


In [96]:
#Convert all of the values in following array arr to degrees:
arr = np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi])
x = np.rad2deg(arr)
print(x)

[ 90. 180. 270. 360.]


In [98]:
#NumPy Trigonometric Functions
x = np.sin(np.pi/2)
print(x)

1.0


In [100]:
#Find sine values for all of the values in arr:
arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])
x = np.sin(arr)
print(x)

[1.         0.8660254  0.70710678 0.58778525]


In [102]:
#Convert Degrees Into Radians
arr = np.array([90, 180, 270, 360])
x = np.deg2rad(arr)
print(x)

[1.57079633 3.14159265 4.71238898 6.28318531]


In [104]:
#Radians to Degrees
arr = np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi])
x = np.rad2deg(arr)
print(x)

[ 90. 180. 270. 360.]


In [106]:
#Finding Angles
x = np.arcsin(1.0)
print(x)

1.5707963267948966


In [108]:
arr = np.array([1, -1, 0.1])
x = np.arcsin(arr)
print(x)

[ 1.57079633 -1.57079633  0.10016742]


In [111]:
#Hypotenues
base = 3
perp = 4
x = np.hypot(base, perp)
print(x)

5.0


In [113]:
#NumPy Hyperbolic Functions
x = np.sinh(np.pi/2)
print(x)

2.3012989023072947


In [115]:
arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])
x = np.cosh(arr)
print(x)

[2.50917848 1.60028686 1.32460909 1.20397209]


In [117]:
#Finding Angles
#Numpy provides ufuncs arcsinh(), arccosh() and arctanh() that produce radian values for corresponding sinh, cosh and tanh values given
x = np.arcsinh(1.0)
print(x)

0.881373587019543


In [119]:
#NumPy Set Operations
import numpy as np
arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])
x = np.unique(arr)
print(x)

[1 2 3 4 5 6 7]


In [121]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])
newarr = np.union1d(arr1, arr2)
print(newarr)

[1 2 3 4 5 6]


In [ ]:
#Finding Intersection